### ISSUE TITLE
Stanza error

### ISSUE THREAD

**Issue by malteos** [openredact/openredact-app#19]
After uploading `demo.txt` I receive this error:

**RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.**

```
backend_1   | 2020-08-03 08:28:33 INFO: Done loading processors!
backend_1   | [2020-08-03 08:28:34 +0000] [8] [ERROR] Exception in ASGI application
backend_1   | Traceback (most recent call last):
backend_1   |   File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
backend_1   |     result = await app(self.scope, self.receive, self.send)
backend_1   |   File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
backend_1   |     return await self.app(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 181, in __call__
backend_1   |     await super().__call__(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 111, in __call__
backend_1   |     await self.middleware_stack(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
backend_1   |     raise exc from None
backend_1   |   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
backend_1   |     await self.app(scope, receive, _send)
backend_1   |   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py", line 86, in __call__
backend_1   |     await self.simple_response(scope, receive, send, request_headers=headers)
backend_1   |   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py", line 142, in simple_response
backend_1   |     await self.app(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
backend_1   |     raise exc from None
backend_1   |   File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
backend_1   |     await self.app(scope, receive, sender)
backend_1   |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 566, in __call__
backend_1   |     await route.handle(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
backend_1   |     await self.app(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
backend_1   |     response = await func(request)
backend_1   |   File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 197, in app
backend_1   |     dependant=dependant, values=values, is_coroutine=is_coroutine
backend_1   |   File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 147, in run_endpoint_function
backend_1   |     return await dependant.call(**values)
backend_1   |   File "/app/endpoints.py", line 123, in find_piis
backend_1   |     res = nerwhal.recognize(wrapper.text, config=nerwhal_config, combination_strategy="smart-fusion")
backend_1   |   File "/usr/local/lib/python3.7/site-packages/nerwhal/core.py", line 102, in recognize
backend_1   |     recognition_results = analyzer.run_recognition(text)
backend_1   |   File "/usr/local/lib/python3.7/site-packages/nerwhal/core.py", line 66, in run_recognition
backend_1   |     return self._run_backends(self.backends.values(), text)
backend_1   |   File "/usr/local/lib/python3.7/site-packages/nerwhal/core.py", line 86, in _run_backends
backend_1   |     return [backend.run(text) for backend in backends]
backend_1   |   File "/usr/local/lib/python3.7/site-packages/nerwhal/core.py", line 86, in <listcomp>
backend_1   |     return [backend.run(text) for backend in backends]
backend_1   |   File "/usr/local/lib/python3.7/site-packages/nerwhal/backends/stanza_ner_backend.py", line 18, in run
backend_1   |     doc = self.stanza_nlp(text)
backend_1   |   File "/usr/local/lib/python3.7/site-packages/stanza/pipeline/core.py", line 176, in __call__
backend_1   |     doc = self.process(doc)
backend_1   |   File "/usr/local/lib/python3.7/site-packages/stanza/pipeline/core.py", line 170, in process
backend_1   |     doc = self.processors[processor_name].process(doc)
backend_1   |   File "/usr/local/lib/python3.7/site-packages/stanza/pipeline/mwt_processor.py", line 33, in process
backend_1   |     preds += self.trainer.predict(b)
backend_1   |   File "/usr/local/lib/python3.7/site-packages/stanza/models/mwt/trainer.py", line 79, in predict
backend_1   |     preds, _ = self.model.predict(src, src_mask, self.args['beam_size'])
backend_1   |   File "/usr/local/lib/python3.7/site-packages/stanza/models/common/seq2seq_model.py", line 261, in predict
backend_1   |     is_done = beam[b].advance(log_probs.data[b])
backend_1   |   File "/usr/local/lib/python3.7/site-packages/stanza/models/common/beam.py", line 84, in advance
backend_1   |     prevK = bestScoresId / numWords
backend_1   | RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.
```

**Comment by langhabel** [comment]
This is due to an incompatibility with stanza 1.0.1 (the latest) and torch 1.6. I limited torch to a lower version to fix the problem.
